const scansData = {
    "god_game": {
        "name": "God game",
        "chapters": [
            {
                "id": 1,
                "title": "Chapitre 71",
                "folder": "./God game/Chapitre 71/",
                "thumbnail": "(god game) team présentation.jpg",
                "images": [
                    "(god game) team présentation.jpg",
                    "1.webp",
                    "2.webp",
                    "3.webp",
                    "4.webp",
                    "5.webp",
                    "6.webp",
                    "7.webp",
                    "8.webp",
                    "9.webp",
                    "10.webp",
                    "11.webp",
                    "12.webp",
                    "13.webp",
                    "14.webp",
                    "15.webp",
                    "16.webp",
                    "17.webp",
                    "18.webp",
                    "19.webp",
                    "20.webp",
                    "21.webp",
                    "22.webp",
                    "23.webp",
                    "24.webp",
                    "25.webp",
                    "26.webp",
                    "27.webp",
                    "28.webp",
                    "29.webp",
                    "30.webp",
                    "31.webp",
                    "32.webp",
                    "33.webp",
                    "34.webp",
                    "35.webp",
                    "36 .webp",
                    "37.webp",
                    "38.webp",
                    "39.webp",
                    "40.webp",
                    "41.webp",
                    "42.webp",
                    "43.webp",
                    "44.webp",
                    "45.webp",
                    "46.webp",
                    "47.webp",
                    "48.webp",
                    "49.webp",
                    "50.webp",
                    "51.webp",
                    "52.webp",
                    "53.webp",
                    "54.webp",
                    "55.webp",
                    "56.webp",
                    "57.webp",
                    "58.webp",
                    "59.webp"
                ],
                "date": "Ajouté récemment"
            },
            {
                "id": 2,
                "title": "Chapitre 72",
                "folder": "./God game/Chapitre 72/",
                "thumbnail": "(god game) team présentation.jpg",
                "images": [
                    "(god game) team présentation.jpg",
                    "0.jpg",
                    "1.jpg",
                    "2.jpg",
                    "3.jpg",
                    "4.jpg",
                    "6.jpg",
                    "7.jpg",
                    "9.jpg",
                    "10.jpg",
                    "11.jpg",
                    "12.jpg",
                    "13.jpg",
                    "14.jpg",
                    "15.jpg",
                    "16.jpg",
                    "17.jpg",
                    "18.jpg",
                    "19.jpg",
                    "20.jpg",
                    "21.jpg",
                    "22.jpg",
                    "23.jpg",
                    "24.jpg",
                    "25.jpg",
                    "26.jpg",
                    "27.jpg",
                    "28.jpg",
                    "29.jpg",
                    "30.jpg",
                    "31.jpg",
                    "33.jpg",
                    "34.jpg",
                    "35.jpg",
                    "37.jpg",
                    "38.jpg",
                    "39.jpg",
                    "40.jpg",
                    "41.jpg",
                    "42.jpg",
                    "43.jpg",
                    "44.jpg",
                    "45.jpg",
                    "46.jpg",
                    "47.jpg",
                    "48.jpg",
                    "49.jpg",
                    "50.jpg",
                    "51.jpg",
                    "52.jpg",
                    "53.jpg",
                    "54.jpg",
                    "55.jpg",
                    "56.jpg",
                    "57.jpg",
                    "58.jpg",
                    "59.jpg",
                    "60.jpg",
                    "61.jpg",
                    "62.jpg",
                    "63.jpg",
                    "64.jpg",
                    "65.jpg",
                    "66.jpg",
                    "67.jpg",
                    "68.jpg",
                    "69.jpg",
                    "70.jpg",
                    "71.jpg",
                    "72.jpg",
                    "73.jpg",
                    "74.jpg",
                    "75.jpg",
                    "76.jpg",
                    "77.jpg",
                    "78.jpg",
                    "79.jpg"
                ],
                "date": "Ajouté récemment"
            },
            {
                "id": 3,
                "title": "Chapitre 73",
                "folder": "./God game/Chapitre 73/",
                "thumbnail": "(god game) team présentation.jpg",
                "images": [
                    "(god game) team présentation.jpg",
                    "0.webp",
                    "2.webp",
                    "3.webp",
                    "4.webp",
                    "5.webp",
                    "7.webp",
                    "8.webp",
                    "9 .webp",
                    "10.webp",
                    "12 .webp",
                    "13.webp",
                    "14.webp",
                    "16.webp",
                    "19.webp",
                    "20.webp",
                    "22.webp",
                    "25.webp",
                    "26.webp",
                    "27.webp",
                    "29.webp",
                    "30.webp",
                    "31.webp",
                    "33.webp",
                    "34.webp",
                    "35.webp",
                    "36.webp",
                    "38.webp",
                    "39.webp",
                    "40.webp",
                    "42.webp",
                    "45.webp",
                    "46.webp",
                    "47.webp",
                    "48.webp",
                    "49.webp",
                    "50.webp",
                    "51.webp",
                    "52.webp",
                    "54.webp",
                    "55.webp",
                    "56.webp",
                    "59.webp",
                    "62.webp",
                    "63.webp",
                    "64.webp",
                    "65.webp",
                    "66.webp",
                    "67.webp",
                    "68.webp",
                    "69.webp",
                    "70.webp",
                    "74.webp",
                    "75.webp",
                    "77.webp",
                    "80.webp",
                    "81.webp",
                    "85.webp",
                    "86.webp",
                    "87.webp",
                    "89.webp"
                ],
                "date": "Ajouté récemment"
            }
        ]
    },
    "lord_of_mysterie": {
        "name": "Lord of mysterie",
        "chapters": [
            {
                "id": 1,
                "title": "chapitre 14",
                "folder": "./Lord of mysterie/chapitre 14/",
                "thumbnail": "0.jpg",
                "images": [
                    "0.jpg",
                    "1.jpg",
                    "2.jpg",
                    "3.jpg",
                    "4.jpg",
                    "5.jpg",
                    "6.jpg",
                    "7.jpg",
                    "8.jpg",
                    "9.jpg",
                    "10 version 2.jpg",
                    "11.jpg",
                    "12.jpg",
                    "13.jpg",
                    "14.jpg",
                    "15.jpg",
                    "16.jpg",
                    "17.jpg",
                    "18.jpg",
                    "19.jpg"
                ],
                "date": "Ajouté récemment"
            }
        ]
    }
};
